import type { Metadata } from "next";
import {Orbitron} from 'next/font/google'
import "./globals.css";
export const metadata: Metadata = {
  title: "Todo-List",
  description: "Generated by create next app",
};
const orb = Orbitron()
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={` ${orb.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
